CHUNKING_PARAMS:
  CHUNK_SIZE: 500
  CHUNK_OVERLAP: 100

DATA_PATHS:
  DATA_DIR: "./data/pdfs"
  VECTOR_STORE_DIR: "./data/vector_store"
  COLLECTION_NAME: "HP_Books_Main"

RAG_MODELS:
  LLM_MODEL: "mistral:latest"
  EMBEDDING_MODEL: "all-minilm:latest"
  TOKENIZER_MODEL: "sentence-transformers/all-MiniLM-L6-v2"
  RERANKER_MODEL: "cross-encoder/ms-marco-MiniLM-L6-v2"