CHUNKING_PARAMS:
  CHUNK_SIZE: 500
  CHUNK_OVERLAP: 100

DATA_PATHS:
  DATA_DIR: "./data/pdfs"
  VECTOR_STORE_DIR: "./data/vector_store"
  COLLECTION_NAME: "HP_Books_Main"

RAG_MODELS:
  LLM_MODEL: "openai/gpt-oss-120b"
  EMBEDDING_MODEL: "voyage-3-large"
  TOKENIZER_MODEL: "voyage-3-large"
  RERANKER_MODEL: "rerank-2.5"